services:
  db:
    image: postgres:17.4
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./drizzle:/docker-entrypoint-initdb.d
  # Use Keycloak as an IdP (like Google) for SSO
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: start-dev
  # Create a client for the app and a user
  keycloak-init:
    image: node:22.14-slim
    volumes:
      - ./scripts/keycloak-init.js:/app/keycloak-init.js
    working_dir: /app
    command: [ "node", "keycloak-init.js" ]
