services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./local.db:/app/local.db
    environment:
      - DB_FILE_NAME=file:local.db
      - NODE_ENV=production
    restart: unless-stopped
